### PR TITLE
Add Monokai Pro and Classic 

### PR DESCRIPTION
**Pull request by minikN**
Hello,

I've added the missing filters:
- Classic (Although there already is a classic variant, this one is slightly different. It's Hazenbergs own variant I guess
- Pro (I've converted the pro theme to match the other filters. The colors where not quite correct and it will benefit from the configuration I've already done)

# Pro
image

# Pro (Classic)
image

### CODE REVIEW

**Comment by minikN** [comment]
@hlissner  @ema2159  @ianpan870102  Please check if everything is like you wanted it in this PR and #601

**Comment by minikN** [comment]
Reference: #532

**Comment by ema2159** [comment]
Sure! The one thing I don't like much is the change in the bg-alt. The contrast is too much, it's too dark. The same would go for the other filters' implementation.

**Comment by minikN** [comment]
> Sure! The one thing I don't like much is the change in the bg-alt. The contrast is too much, it's too dark. The same would go for the other filters' implementation.

I'll review it. From the top of my head I can't tell you where I picked the color from. Might have been implemented like this in VS Code (where I took the color from) or I chose it myself because it was missing.

If the latter is the case, I'll adjust it. But this will take a couple of days as I'm super stumped with work atm.
Alternatively, your or @ianpan870102 can recommend a different color.

**Comment by ema2159** [comment]
I think I can pick some from VS Code. I think I know which ones you picked, but there is another option to pick also in VS Code which I'd rather choose.

**Comment by minikN** [comment]
bump

**Review by hlissner — CHANGES_REQUESTED** [review]
Sorry for the late response. Would you mind resolving the conflicts? Then I think this will be ready to merge.

**Comment by minikN** [comment]
Sorry but I don't use doom/doom-themes anymore.

**Pull request closed without merging**
