### PR TITLE
theme: add doom-catppuccin

### PR DESCRIPTION
**Pull request by mangkoran**
This PR adds initial implementation of doom-catpppuccin theme, a theme based on [catppuccin](https://github.com/catppuccin/catppuccin) color scheme. Currently it only supports 3 of catppuccin's dark palettes (because I think the light palette need different theme name).

Will update with several screenshots.

This PR is mostly still WIP. Feel free to suggest any improvement!

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] My changes are visual; I've included before and after screenshots.
- [x] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.
- [x] This a draft PR; I need more time to finish it.

### CODE REVIEW

**Comment by NamesCode** [comment]
Hey this is the current maintainer for Catppuccin Emacs. Seeing as this does not have latte support, could I take this code as a base and improve upon it to support more?

**Comment by mangkoran** [comment]
Yes you are welcome! I will grant you the permission on my fork.

**Comment by NamesCode** [comment]
Thanks! I will get to it tomorrow :D

**Comment by mangkoran** [comment]
@NamesCode It seems it would be better if we separate `latte` variant (e.g. `doom-catppuccin-light`). However, if you want it to be one file/theme, the file/theme name should be updated (currently it's `doom-catppuccin-dark`).

**Review by port19x — COMMENTED** [review]
Looks reasonable.
I'd love for this to be merged soon-ish

**Comment by port19x** [comment]
> @port19x Apologize but currently I am busy with irl stuff. Please be patient or if you could, you may contribute to the code.
> 
> Backlog is:
> 
> 1. We need to separate `catppuccin-dark` (the rest 3) and `catppuccin-light` (latte). Why? Because light variant I believe has different syntax highlighting rules than simply change the color to its light counterparts.

I'll look into it. Been looking for an opportunity to hack on some elisp

**Comment by mangkoran** [comment]
Closed in favor of https://github.com/catppuccin/emacs. Thank you for all amazing catppuccin contributors!

**Pull request closed without merging**
