### PR TITLE
theme: add doom-oksolar-{dark,light}

### PR DESCRIPTION
**Pull request by logc**
These themes are a variation on Solarized based on a new colorspace called [OKLab](https://bottosson.github.io/posts/oklab/). A description of the themes by the author can be found [in this blog post](https://meat.io/oksolar).

The implementation in this commit is based on the `doom-solarized` themes, with the following differences:

- in the light theme, `hl-line` has a background of `base1` instead of `base3` because otherwise syntax highlight mixes with background.

~Fixes #0000~
~References #0000~
~Replaces #0000~

# Screenshots

## doom-oksolar-dark

Screenshot 2022-11-21 at 21 46 32

## doom-oksolar-light

Screenshot 2022-11-21 at 21 45 02

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] My changes are visual; I've included before and after screenshots.
- [x] ~I am blindly checking these off.~
- [X] Any relevant issues or PRs have been linked to.

### CODE REVIEW

**Comment by logc** [comment]
I read the original blog posts some days ago and thought that the OKSolar themes are really interesting work, because it solves low contrast, a known weak point of Solarized (which is otherwise a wonderful theme that I have used for many years).

This is my first theme contribution, and I am not fully confident in the changes here. The scale of colors `base0` to `base8` should go from "close to bg color" to "close to fg color". However, there are not enough colors in the scale defined in the original post to cover all those slots. I have started directly the `bg` color in one instance, and left the last color unchanged in the other instance. Any help here? What are possible alternatives?

I am not sure if this is related, but one place where contrast is still not working is in source code blocks in Markdown.

Screenshot 2022-11-21 at 22 10 14

**Comment by logc** [comment]
I have managed to understand better the palette used in Solarized and OKSolar after the author of OKSolar pointed me to [the right documentation](https://ethanschoonover.com/solarized/#usage-development) (thanks again!).

I have also managed to select better the background color for vertico selections and Markdown code blocks.

Screenshot 2022-11-27 at 00 16 56

I am using the dark variant as my daily driver. If there are other issues discovered, I would be happy to fix them. Otherwise, I think this theme is ready to be reviewed.

**Comment by Game-Warrior** [comment]
Screenshot 2023-02-23 at 6 29 04 PM
 I am experiencing a lack or readability when attempting to select stuff from M-x. I like this theme otherwise but this makes is very difficult for me to use.

**Comment by logc** [comment]
@Game-Warrior : I have looked into it. There was a weird interaction between `bg-alt`, `base1` and `region` colors. Setting `region` to `base1` made text selection readable but vertical selection unreadable. And setting it to e.g. `base0` did the opposite. 

In the end, I have taken a hint from the [doom one theme](https://github.com/doomemacs/themes/blob/master/themes/doom-one-theme.el) and modified slightly the `bg-alt` color for region. Now both text selection and vertical selection seem to work. Can you please try it out?

**Comment by logc** [comment]
Here is an example with selected text and an `M-x` vertical selection, both readable now.
Screenshot 2023-03-03 at 21 39 05

**Comment by Game-Warrior** [comment]
@logc Looks great the selection menu now renders properly.

**Review by gagbo — APPROVED** [review]

**Comment by logc** [comment]
@gagbo thanks for approving this PR, but it seems merging it requires a review by someone with write access. Do you know who that is?

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Great work! Sorry for taking so long to merge this, but thanks for your PR!

**Pull request merged**
