### PR TITLE
theme: add doom-feather-{dark,light}

### PR DESCRIPTION
**Pull request by Plunne**
Hi!

This is my theme in both colors : Feather Dark and Light.

_Feather means plume in french which my nickname is derivated from._

**Dashboard + Minibuffer**

**Org Mode + Treemacs**

**Prog Mode + Treesitter + Rainbow parentheses + DAP**

Thanks!

### CODE REVIEW

**Comment by jeetelongname** [comment]
Hi! 

Do you mind ammending your commit to conform to our conventions
and do you mind adding your themes to the list in the README

thanks! Great work!

**Comment by Plunne** [comment]
> Hi!
> 
> Do you mind amending your commit to conform to our conventions and do you mind adding your themes to the list in the README
> 
> thanks! Great work!

Hi! I've never heard of a convention. I didn't add it in the README. Henrik just said to me putting the themes into the themes directory then PR. :)

**Review by hlissner — CHANGES_REQUESTED** [review]
Thanks for the PR! I'll be happy to merge this soon, but I've changed it to a draft for now because it needs a little work. Mainly:

1. To add the theme to the list in [README.md](https://github.com/doomemacs/themes/blob/master/README.md#theme-list).
2. And to correct the git message to conform to [our git conventions](https://discourse.doomemacs.org/t/git-conventions/2407).
3. The issues I've highlighted in my review.

If you're not sure how to these two, don't worry about it; I'll do it myself next week (sorry, a bit swamped atm).

**Comment by Plunne** [comment]
> Thanks for the PR! I'll be happy to merge this soon, but I've changed it to a draft for now because it needs a little work. Mainly:
> 
>     1. To add the theme to the list in [README.md](https://github.com/doomemacs/themes/blob/master/README.md#theme-list).
> 
>     2. And to correct the git message to conform to [our git conventions](https://discourse.doomemacs.org/t/git-conventions/2407).
> 
>     3. The issues I've highlighted in my review.
> 
> 
> If you're not sure how to these two, don't worry about it; I'll do it myself next week (sorry, a bit swamped atm).

Yes, no problem, i let you do this, then you'll be sure it is right. Thanks! :blush:

**Pull request closed without merging**
